obj-$(CONFIG_NET_PICO_SUPPORT_IPV4) += pico_ipv4.o
obj-$(CONFIG_NET_PICO_SUPPORT_ICMP4) += pico_icmp4.o
obj-$(CONFIG_NET_PICO_SUPPORT_TCP) += pico_tcp.o pico_socket_tcp.o
obj-$(CONFIG_NET_PICO_SUPPORT_UDP) += pico_udp.o pico_socket_udp.o

obj-$(CONFIG_NET_PICO_SUPPORT_ETH) += pico_arp.o
obj-$(CONFIG_NET_PICO_SUPPORT_DEVLOOP) += pico_dev_loop.o
obj-y += pico_dev_null.o

obj-$(CONFIG_NET_PICO_SUPPORT_DHCP_CLIENT) += pico_dhcp_client.o
obj-$(CONFIG_NET_PICO_SUPPORT_DHCP_CLIENT) += pico_dhcp_common.o

#obj-y += pico_dev_mock.o
#obj-y += pico_dev_pcap.o
#obj-y += pico_dev_tun.o
#obj-y += pico_dev_vde.o
#obj-y += pico_dhcp_client.o
#obj-y += pico_dhcp_common.o
#obj-y += pico_dhcp_server.o
#obj-y += pico_dns_client.o
#obj-y += pico_icmp6.o
#obj-y += pico_igmp.o
#obj-y += pico_ipfilter.o
#obj-y += pico_ipv6.o
#obj-y += pico_ipv6_nd.o
#obj-y += pico_mm.o
#obj-y += pico_nat.o
#obj-y += pico_olsr.o
#obj-y += pico_posix.o
#obj-y += pico_slaacv4.o
#obj-y += pico_sntp_client.o
