# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_CMD_PICOTCP_TEST_IPV4) += picotcp_test_ipv4.o
obj-$(CONFIG_CMD_PICOTCP_IFCONFIG) += picotcp_ifconfig.o
obj-$(CONFIG_CMD_PICOTCP_ROUTE) += picotcp_route.o
obj-$(CONFIG_CMD_PICOTCP_DHCLIENT) += picotcp_dhclient.o
obj-$(CONFIG_CMD_PICOTCP_PICOPING) += picoping.o
obj-$(CONFIG_CMD_PICOTCP_PICOHOST) += picohost.o
