#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=nor
root=nor

uimage=uImage-mx35-3-stack
jffs2=root-mx35-3-stack.jffs2

autoboot_timeout=3

nfsroot="/path/to/nfs_root"
bootargs="console=ttymxc0,115200"

nor_parts="256k(uboot)ro,128k(ubootenv),2048k(kernel),-(root)"
rootpart_nor="/dev/mtdblock3"
nand_parts="256k(uboot)ro,256k(ubootenv),2048k(kernel),-(root)"
rootpart_nand="/dev/mtdblock7"

# use 'dhcp' to do dhcp in uboot and in kernel
ip=dhcp

# or set your networking parameters here
eth0.ipaddr=192.168.42.250
eth0.netmask=255.255.0.0
eth0.gateway=192.168.23.2
eth0.serverip=192.168.23.2
#eth0.ethaddr=aa.bb.cc.dd.ee.ff

