obj-y += start.o
obj-$(CONFIG_CPU_JZ4740) += csrc-jz4740.o reset-jz4740.o
obj-$(CONFIG_CPU_JZ4755) += csrc-jz4750.o reset-jz4750.o
obj-$(CONFIG_CPU_JZ4770) += csrc-jz4770.o reset-jz4770.o \
	lowlevel_init-jz4770.o
